# Generated by Django 5.0.12 on 2025-02-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('alert_time', models.DateTimeField()),
                ('alert_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=50)),
            ],
            options={
                'db_table': 'alert_history',
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_loc', models.JSONField()),
                ('end_loc', models.JSONField()),
                ('optm_route', models.JSONField()),
                ('distance', models.FloatField()),
                ('estimated_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'route_optimization',
            },
        ),
        migrations.CreateModel(
            name='VehicleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('anal_time', models.DateTimeField()),
                ('avg_speed', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('distance', models.FloatField()),
                ('anom_flag', models.BooleanField(default=False)),
                ('adtn_info', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'vehicle_analytics',
            },
        ),
        migrations.CreateModel(
            name='VehicleSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('speed', models.FloatField()),
                ('fuel_level', models.FloatField()),
                ('engine_temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_sensor_data',
            },
        ),
    ]
