# Generated by Django 5.0.12 on 2025-02-12 07:43

import djongo.models.fields
import vehicle_demo.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('gps', djongo.models.fields.EmbeddedModelField(model_container=vehicle_demo.users.models.GPSData, null=True)),
                ('speed', models.FloatField()),
                ('temperature', models.FloatField()),
                ('image_url', models.URLField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
