# Generated by Django 5.0.12 on 2025-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vehiclesensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('alert_time', models.DateTimeField()),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'SENT'), ('FAILED', 'FAILED')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_loc', models.JSONField()),
                ('end_loc', models.JSONField()),
                ('optm_route', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('anal_time', models.DateTimeField()),
                ('avg_speed', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('anom_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
