services:
  docs:
    image: vehicle_demo_local_docs
    container_name: vehicle_demo_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./vehicle_demo:/app/vehicle_demo:z
    ports:
      - '9000:9000'
    command: /start-docs
